name: CI
on: [pull_request]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.prod.yaml up -d
      - run: docker exec desafio5-app dockerize -timeout=200s -wait=http://localhost:3000
      - run: docker exec desafio5-app npm run test